version: '3'
services:
  mongo:
    image: 'mongo'
    ports:
    - '27017:27017'
  sensors:
    build:
      context: .
      dockerfile: sensors/Dockerfile
    depends_on:
    - mongo
    links:
      - mongo
    restart: on-failure