version: '3'
services:
  mongo:
    image: 'mongo'
    ports:
    - "27017:27017"

  sensors:
    build:
      context: .
      dockerfile: sensors/Dockerfile
    depends_on:
    - mongo
    ports:
    - "1000:1000"
    links:
    - mongo
    restart: on-failure

  backend:
   build:
     context: .
     dockerfile: backend/Dockerfile
   depends_on:
   - mongo
   ports:
   - "80:80"
   links:
   - mongo
   restart: on-failure

  mongo-express:
   image: "mongo-express"
   ports:
   - "90:8081"