// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proposal.proto

package proposal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Proposal struct {
	IP                   string               `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Price                int32                `protobuf:"varint,2,opt,name=Price,proto3" json:"Price,omitempty"`
	TotalCost            int32                `protobuf:"varint,3,opt,name=TotalCost,proto3" json:"TotalCost,omitempty"`
	DeltaPrice           int32                `protobuf:"varint,4,opt,name=DeltaPrice,proto3" json:"DeltaPrice,omitempty"`
	Salt                 int32                `protobuf:"varint,5,opt,name=Salt,proto3" json:"Salt,omitempty"`
	TTL                  int32                `protobuf:"varint,6,opt,name=TTL,proto3" json:"TTL,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,7,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3ac5ce23bf32d05, []int{0}
}

func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *Proposal) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Proposal) GetTotalCost() int32 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

func (m *Proposal) GetDeltaPrice() int32 {
	if m != nil {
		return m.DeltaPrice
	}
	return 0
}

func (m *Proposal) GetSalt() int32 {
	if m != nil {
		return m.Salt
	}
	return 0
}

func (m *Proposal) GetTTL() int32 {
	if m != nil {
		return m.TTL
	}
	return 0
}

func (m *Proposal) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func init() {
	proto.RegisterType((*Proposal)(nil), "proposal.Proposal")
}

func init() { proto.RegisterFile("proposal.proto", fileDescriptor_c3ac5ce23bf32d05) }

var fileDescriptor_c3ac5ce23bf32d05 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xd9, 0xb4, 0xa9, 0xed, 0x54, 0x8a, 0x0c, 0x1e, 0x96, 0x22, 0x1a, 0x3c, 0xe5, 0xb4,
	0x05, 0x3d, 0x7b, 0xd2, 0x4b, 0xc1, 0xc3, 0x12, 0xd7, 0xb3, 0x6c, 0xed, 0x1a, 0x02, 0x1b, 0x66,
	0xc9, 0x4e, 0x7e, 0xa9, 0x7f, 0x48, 0xb2, 0x6b, 0xd0, 0xdb, 0xbc, 0xef, 0x7d, 0x73, 0x78, 0xb0,
	0x0b, 0x03, 0x05, 0x8a, 0xd6, 0xab, 0x30, 0x10, 0x13, 0xae, 0xe7, 0xbc, 0xbf, 0x6b, 0x89, 0x5a,
	0xef, 0x0e, 0x89, 0x9f, 0xc6, 0xaf, 0x03, 0x77, 0xbd, 0x8b, 0x6c, 0xfb, 0x90, 0xd5, 0xfb, 0x6f,
	0x01, 0x6b, 0xfd, 0x6b, 0xe3, 0x0e, 0x8a, 0xa3, 0x96, 0xa2, 0x12, 0xf5, 0xa6, 0x29, 0x8e, 0x1a,
	0xaf, 0xa1, 0xd4, 0x43, 0xf7, 0xe9, 0x64, 0x51, 0x89, 0xba, 0x6c, 0x72, 0xc0, 0x1b, 0xd8, 0x18,
	0x62, 0xeb, 0x9f, 0x29, 0xb2, 0x5c, 0xa4, 0xe6, 0x0f, 0xe0, 0x2d, 0xc0, 0x8b, 0xf3, 0x6c, 0xf3,
	0xe3, 0x32, 0xd5, 0xff, 0x08, 0x22, 0x2c, 0xdf, 0xac, 0x67, 0x59, 0xa6, 0x26, 0xdd, 0x78, 0x05,
	0x0b, 0x63, 0x5e, 0xe5, 0x2a, 0xa1, 0xe9, 0xc4, 0x27, 0xb8, 0xf4, 0x36, 0xf2, 0xc7, 0x18, 0xce,
	0x96, 0xdd, 0x59, 0x5e, 0x54, 0xa2, 0xde, 0x3e, 0xec, 0x55, 0x9e, 0xa3, 0xe6, 0x39, 0xca, 0xcc,
	0x73, 0x9a, 0xed, 0xe4, 0xbf, 0x67, 0xfd, 0xb4, 0x4a, 0xc2, 0xe3, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x56, 0x63, 0x35, 0x55, 0x19, 0x01, 0x00, 0x00,
}
